version: 0.0
os: windows
phases:
  pre_build:
    commands:
     - New-Item -ItemType Junction -Path C:\Src -Value $Env:CODEBUILD_SRC_DIR
     - cd C:\Src  
    
  build:
    commands:
     - msbuild 